export default {
  products: [
    {
      _id: "1",
      name: "Hiskywin Full Zip Running Shirts Thermal Workout",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Nike Full-Zip Hoodie Mens Workout Sweatshirt",
      category: "Shirts",
      image: "images/product-2.jpg",
      price: 40,
      brand: "Nike",
      rating: 5,
      numReviews: 51,
    },
    {
      _id: "3",
      name: "Adidas Mens Long Sleeve Hoodie",
      category: "Shirts",
      image: "images/product-3.jpg",
      price: 60,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Under Armour Mens Sportstyle Tricot Joggers",
      category: "Trousers",
      image: "images/product-4.jpg",
      price: 40,
      brand: "Under Armour",
      rating: 5,
      numReviews: 51,
    },
    {
      _id: "5",
      name: "Nike Mens Running Shorts",
      category: "Shirts",
      image: "images/product-5.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Nike Full-Zip Hoodie Mens Workout Sweatshirt",
      category: "Shirts",
      image: "images/product-6.jpg",
      price: 40,
      brand: "Nike",
      rating: 5,
      numReviews: 51,
    },
  ],
};
